REGISTRY = registry.gitlab.com
NAMESPACE = latipium
REPOSITORY = website
IMAGE = mysql-base
BASE_REGISTRY = registry.gitlab.com
BASE_NAMESPACE = latipium
BASE_REPOSITORY = website
BASE_IMAGE = base

include ../../base.mk

.cache/deps: Dockerfile
