language: node_js
node_js:
- "node"
before_install:
- npm install
- bundle install
script: bash ./compile.sh
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
addons:
  apt:
    packages:
    - ruby
