// _8bbd99ac.Designer.cs
//
// Copyright (c) 2016 Zach Deibert.
// All Rights Reserved.
//
// This code was auto-generated from commit 8bbd99ac:
// <auto-generated />
namespace Com.Latipium.Website.Apis.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _8bbd99ac : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_8bbd99ac));
        
        string IMigrationMetadata.Id
        {
            get { return "201607081542131__8bbd99ac"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}

