// _bc76d87c.Designer.cs
//
// Copyright (c) 2016 Zach Deibert.
// All Rights Reserved.
//
// This code was auto-generated from commit bc76d87c:
// <auto-generated />
namespace Com.Latipium.Website.Apis.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _bc76d87c : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_bc76d87c));
        
        string IMigrationMetadata.Id
        {
            get { return "201607081218007__bc76d87c"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}

