// _df503cb9.Designer.cs
//
// Copyright (c) 2016 Zach Deibert.
// All Rights Reserved.
//
// This code was auto-generated from commit df503cb9:
// <auto-generated />
namespace Com.Latipium.Website.Apis.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _df503cb9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_df503cb9));
        
        string IMigrationMetadata.Id
        {
            get { return "201607241528146__df503cb9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}

