REGISTRY = registry.gitlab.com
NAMESPACE = latipium
REPOSITORY = website
IMAGE = config
BASE_REGISTRY = registry.gitlab.com
BASE_NAMESPACE = latipium
BASE_REPOSITORY = website
BASE_IMAGE = config-base

include ../base.mk

.cache/deps: Dockerfile run.sh
