REGISTRY = registry.gitlab.com
NAMESPACE = latipium
REPOSITORY = website
IMAGE = config-base
BASE_REGISTRY = docker.io
BASE_NAMESPACE = resin
BASE_REPOSITORY = armv7hf-debian-qemu
BASE_IMAGE = latest

include ../../base.mk

.cache/deps: Dockerfile
