stages:
- transpile
- mockGeneration
- build
- dockerRoot
- dockerBase
- dockerImage
- deploy

.base_template: &base
  tags:
  - docker
  script:
  - make build-$CI_BUILD_NAME
  only:
  - master

.docker_template: &docker
  <<: *base
  image: zachdeibert/make:1.11.1
  tags:
  - docker
  - privileged
  services:
  - docker:1.11.1-dind
  cache:
    key: "$CI_BUILD_NAME"
    paths:
    - .cache/
  dependencies:
  - nothing

typescript:
  <<: *base
  stage: transpile
  image: zachdeibert/typescript:latest
  artifacts:
    paths:
    - http/content/js

nothing:
  <<: *base
  stage: transpile
  image: zachdeibert/debian-dev:latest

libnunit-core-interfaces-mock:
  <<: *base
  stage: mockGeneration
  image: zachdeibert/debian-dev:latest
  cache:
    paths:
    - apis/base/libnunit-core-interfaces2.6.3-cil
  artifacts:
    paths:
    - apis/base/libnunit-core-interfaces2.6.3-cil.deb
  dependencies:
  - nothing

jekyll:
  <<: *base
  stage: build
  image: zachdeibert/jekyll:3.1.6
  artifacts:
    paths:
    - http/content/_site/
  dependencies:
  - typescript

apis:
  <<: *base
  stage: build
  image: zachdeibert/mono-make:4.2.3.4
  artifacts:
    paths:
    - apis/bin/
  cache:
    paths:
    - apis/obj/
  dependencies:
  - nothing

nsis:
  <<: *base
  stage: build
  image: zachdeibert/nsis:latest
  artifacts:
    paths:
      - http/content/electron/Latipium_Setup.exe
  dependencies:
  - typescript

docker-base:
  <<: *docker
  stage: dockerRoot

docker-apis-base:
  <<: *docker
  stage: dockerBase
  dependencies:
  - libnunit-core-interfaces-mock

docker-cloudflare-base:
  <<: *docker
  stage: dockerBase

docker-config-base:
  <<: *docker
  stage: dockerBase

docker-http-base:
  <<: *docker
  stage: dockerBase

docker-mysql-base:
  <<: *docker
  stage: dockerBase

docker-nuget-base:
  <<: *docker
  stage: dockerBase

docker-apis:
  <<: *docker
  stage: dockerImage
  dependencies:
  - apis

docker-cloudflare:
  <<: *docker
  stage: dockerImage

docker-config:
  <<: *docker
  stage: dockerImage

docker-http:
  <<: *docker
  stage: dockerImage
  dependencies:
  - jekyll
  - nsis

docker-mysql:
  <<: *docker
  stage: dockerImage

docker-nuget:
  <<: *docker
  stage: dockerImage

deploy:
  <<: *base
  tags:
  - shell
  - linux
  - latipium
  - deploy
  stage: deploy
  dependencies:
  - nothing
  environment: production
