version: '2'
services:
  http:
    image: registry.gitlab.com/latipium/website:http
    ports:
    - "443:443"
    networks:
    - latipium
    environment:
    - "constraint:node==latipium-manager"
    extra_hosts:
    - "content-server:{{ content ip }}"
    volumes:
    - nuget:/var/local/packagefiles
    restart: on-failure:100
  config:
    image: registry.gitlab.com/latipium/website:config
    ports:
    - "80"
    networks:
    - latipium
    volumes:
    - config:/var/www/html
    extra_hosts:
    - "content-server:{{ content ip }}"
    restart: on-failure:100
  nuget:
    image: registry.gitlab.com/latipium/website:nuget
    ports:
    - "9000"
    networks:
    - latipium
    restart: on-failure:100
  mysql:
    image: registry.gitlab.com/latipium/website:mysql
    ports:
    - "3306"
    networks:
    - latipium
    volumes:
    - mysql:/var/lib/mysql
    restart: on-failure:100
  apis:
    image: registry.gitlab.com/latipium/website:apis
    ports:
    - "9000"
    networks:
    - latipium
    environment:
    - "constraint:node==latipium-manager"
    volumes:
    - nuget:/var/local/packages
    restart: on-failure:100
  cloudflare:
    image: registry.gitlab.com/latipium/website:cloudflare
    networks:
    - latipium
networks:
  latipium:
    driver: overlay
volumes:
  config: {}
  nuget: {}
  mysql: {}
